FROM nginx:alpine

ENV NGINX_HOST=localhost
ENV NGINX_PORT=80

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /var/www/html -p && touch /var/www/html/index.php

EXPOSE  80




